syntax = "proto3";

package docs;

option go_package = "github.com/spitikos/spitikos/api/proto/docs;docsv1";

import "google/protobuf/timestamp.proto";

// DocsService manages the documentation lifecycle.
service DocsService {
  // Sync is triggered by a webhook. It receives a complete list of all
  // current document slugs, fetches their content, and updates the cache.
  rpc Sync(SyncRequest) returns (SyncResponse) {}

  // GetSlugs retrieves a list of all available document slugs from the cache.
  rpc GetSlugs(GetSlugsRequest) returns (GetSlugsResponse) {}

  rpc GetDoc(GetDocRequest) returns (GetDocResponse) {}
}

message SyncRequest {
  repeated string paths = 1;
}

message SyncResponse {
  map<string, SyncStatus> status = 1; // slug -> status
}

// GetSlugsRequest is the request message for the GetSlugs RPC.
message GetSlugsRequest {}

// GetSlugsResponse contains the list of all document slugs.
message GetSlugsResponse {
  // The list of all slugs currently available in the cache.
  repeated string slugs = 1;
}

message GetDocRequest {
  string slug = 1;
}

message GetDocResponse {
  Doc doc = 1;
}

message SyncStatus {
  bool GetContent = 1;
  bool GetLatestCommit = 2;
  bool MarshalDoc = 3;
  bool CacheDoc = 4;
}

message Doc {
  string title = 1;
  google.protobuf.Timestamp modified = 2;
  string content = 3;
}
