version: "3"

tasks:
  run:
    desc: Run the main application.
    dotenv: ["./config/config.env"]
    cmds:
      - telepresence connect
      - go run ./cmd/server/main.go
    silent: true

  buf:push:
    desc: Push the current proto files to the remote repository.
    cmds:
      - buf push
    silent: true

  buf:lint:
    desc: Lint the current proto files.
    cmds:
      - buf lint
    silent: true
