server:
  port: 50051
  streamIntervalSeconds: 5
prometheus:
  address: https://prometheus.taehoonlee.cloud
  queryRangeStepSeconds: 15
redis:
  address: redis-master.redis.svc.cluster.local:6379
github:
  owner: spitikos
