syntax = "proto3";

package prometheus.v1;

option go_package = "spitikos/api/prometheus/v1";

import "google/protobuf/timestamp.proto";
import "prometheus/v1/types.proto";

service PrometheusService {
  rpc Query(QueryRequest) returns (QueryResponse) {}
  rpc QueryRange(QueryRangeRequest) returns (QueryRangeResponse) {}
  rpc StreamQuery(QueryRequest) returns (stream QueryResponse) {}
  rpc StreamQueryRange(QueryRangeRequest) returns (stream QueryRangeResponse) {}
}

message QueryRequest {
  string query = 1;
}

message QueryResponse {
  repeated Sample data = 1;
}

message QueryRangeRequest {
  string query = 1;
  google.protobuf.Timestamp since = 2;
}

message QueryRangeResponse {
  repeated SampleStream data = 1;
}
