name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Call Release Workflow
    permissions:
      contents: write
      packages: write
    uses: spitikos/spitikos/.github/workflows/release.yaml@main
    with:
      chart_path: '["charts/api/api-server"]'
      image_name: api
      image_tag: ${{ github.sha }}
    secrets: inherit
